global:

route:
  receiver: calert
  group_interval: 60s
  repeat_interval: 24h
  group_by: ['room', 'alertname']
  group_wait: 30s


    #receivers:
    #  - name: discord_webhook
    #    webhook_configs:
    #    - url: http://discord-alerts:9094
    #      send_resolved: true
receivers:
  - name: 'calert'
    webhook_configs:
    - url: 'http://calert:6000/dispatch'
      send_resolved: true
