version: "3.9"
services:
  grafana:
    image: grafana/grafana:${GRAFANA_VERSION}
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana_data:/var/lib/grafana
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - GF_SECURITY_ADMIN_USER=${ADMIN_USER}
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_AUTH_PROXY_ENABLED=true
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    restart: unless-stopped
    expose:
      - "3000"

  prometheus:
    image: prom/prometheus:v2.32.1
    container_name: prometheus
    ports:
    - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - ./prometheus_data:/prometheus
      - ./prometheus/alerts.rules.yaml:/etc/prometheus/alerts.rules
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    restart: unless-stopped
    expose:
      - "9090"

  nodeexporter:
    image: prom/node-exporter:v1.3.1
    container_name: nodeexporter
    ports:
      - "9100:9100"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.rootfs=/rootfs'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
    restart: unless-stopped
    expose:
      - 9100
  discord-alerts:
    image: benjojo/alertmanager-discord
    container_name: discord-alerts
    restart: unless-stopped
    environment:
      - DISCORD_WEBHOOK=${VAR_DISCORD_WEBHOOK}

  blackbox_exporter:
    image: prom/blackbox-exporter
    container_name: blackbox
    dns: 8.8.8.8
    restart: always
    ports:
      - "9115:9115"
    volumes:
      - "./blackbox:/config"
    command:
      - '--config.file=/config/blackbox.yml'
  alertmanager:
    image: prom/alertmanager:v0.21.0
    container_name: alertmanager
    restart: unless-stopped
    command:
      - "--config.file=/prometheus/alertmanager.yaml"
    volumes:
      - "./alertmanager/alertmanager.yaml:/prometheus/alertmanager.yaml"
    ports:
      - "9093:9093"