groups:
- name: Web blackbox
  rules:
  - alert: ❌ Alerta - Status do site ❌
    expr: probe_success == 0
    for: 1m
    labels:
      severity: ALTA
    annotations:
      description: |
        - Detalhe: Sonda falhou
        - Valor: {{ $value }}
        - Instância: {{ $labels.instance }}
    

  - alert: ❌ Alerta - Falha na recarga da configuração do Blackbox ❌
    expr: blackbox_exporter_config_last_reload_successful != 1
    for: 5m
    labels:
      severity: ATENÇÃO
    annotations:
      description: |
        - Detalhe: Falha na recarga da configuração do Blackbox
        - Valor: {{ $value }}
        - Instância: {{ $labels.instance }}


  - alert: ⚠️ Alerta - Consulta do site demorou muito  ⚠️
    expr: avg_over_time(probe_duration_seconds[1m]) > 1
    for: 1m
    labels:
      severity: ATENÇÃO
    annotations:
      description: |
        - Detalhe: Sonda Blackbox levou mais de 1 segundo para ser concluída
        - Valor: {{ $value }} segundos
        - Instância: {{ $labels.instance }}


  - alert: ❌ Alerta - Status code ❌
    expr: probe_http_status_code <= 199 OR probe_http_status_code >= 400
    for: 5m
    labels:
      severity: ALTA
    annotations:
      description: |
        - Detalhe: Código de status HTTP diferente de 200-399
        - Status Code: {{ $value }}
        - Site: {{ $labels.instance }}


  - alert: ❌ Alerta - Certificado SSL do site está expirado ❌
    expr: round((last_over_time(probe_ssl_earliest_cert_expiry[10m]) - time()) / 86400, 0.1) < 0
    for: 5m
    labels:
      severity: ALTA
    annotations:
      description: |
        - Detalhe: Certificado SSL expirou
        - Dias de Expiração: {{ $value }}
        - Instância: {{ $labels.instance }}


  - alert: ⚠️ Alerta - Certificado SSL do site irá expirar em breve ⚠️
    expr: 3 <= round((last_over_time(probe_ssl_earliest_cert_expiry[10m]) - time()) / 86400, 0.1) < 30
    for: 5m
    labels:
      severity: ATENÇÃO
    annotations:
      description: |
        - Detalhe: Certificado SSL expirará em menos de 30 dias
        - Dias de Expiração: {{ $value }}
        - Instância: {{ $labels.instance }}


  - alert: ⚠️ Alerta - Consulta HTTP lenta ⚠️
    expr: avg_over_time(probe_http_duration_seconds[1m]) > 1
    for: 1m
    labels:
      severity: ATENÇÃO
    annotations:
      description: |
        - Detalhe: Requisição HTTP levou mais de 1 minuto
        - Valor: {{ $value }} segundos
        - Instância: {{ $labels.instance }}


  - alert: ⚠️ Alerta - Consulta via ping está lenta ⚠️
    expr: avg_over_time(probe_icmp_duration_seconds[1m]) > 1
    for: 1m
    labels:
      severity: ATENÇÃO
    annotations:
      description: |
        - Detalhe: Ping do Blackbox levou mais de 1 minuto
        - Valor: {{ $value }} segundos
        - Instância: {{ $labels.instance }}


