global:
  scrape_interval:     60s
  evaluation_interval: 60s

alerting:
  alertmanagers:
  - scheme: http
  - static_configs:
      - targets: ['alertmanager:9093']
rule_files:
  - alerts.rules

scrape_configs:

  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['prometheus:9090']
  
  - job_name: 'node'
    scrape_interval: 10s
    static_configs:
    - targets: ['nodeexporter:9100']

  - job_name: 'blackbox'
    metrics_path: /probe
    scrape_interval: 120s
    params:
        module: [http_2xx]
    static_configs:
        - targets:
          - https://uol.com.br
          - https://google.com
          - https://github.com
          - https://linkedin.com
          - https://globo.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox_exporter:9115  