{
 "title": "blackbox exporter http Dashboard",
 "description": "blackbox_exporter HTTP monitoring panel",
 "tags": [
  "http/https",
  "blackbox_exporter",
  "web",
  "prometheus"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "project",
    "label": "project",
    "query": {
     "query": "label_values(probe_http_status_code, project)"
    }
   },
   { "name": "app", "label": "app", "query": { "query": "label_values(app)" } }
  ]
 },
 "panels": [
  { "title": "HTTP Monitoring Information", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instance status percentage",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_success{project=~\"$project\", app=~\"$app\"} == 1)",
     "legendFormat": "Success status instance"
    },
    {
     "expr": "count(probe_success{project=~\"$project\", app=~\"$app\"} == 0)",
     "legendFormat": "Failed status instance"
    }
   ]
  },
  {
   "title": "Total Sites Dealersites",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_success{project=~\"$project\", app=~\"$app\"})"
    }
   ]
  },
  {
   "title": "Detailed Information",
   "type": "table",
   "gridPos": { "h": 11, "w": 14, "x": 10, "y": 1 },
   "targets": [
    {
     "expr": "probe_success{project=~\"$project\", app=~\"$app\"}"
    },
    {
     "expr": "probe_http_status_code{project=~\"$project\", app=~\"$app\"}"
    },
    {
     "expr": "probe_ssl_earliest_cert_expiry{project=~\"$project\", app=~\"$app\"} - time()"
    },
    {
     "expr": "probe_ssl_earliest_cert_expiry{project=~\"$project\", app=~\"$app\"} * 1000"
    },
    {
     "expr": "sum(probe_http_duration_seconds{project=~\"$project\", app=~\"$app\"}) by (instance)"
    },
    {
     "expr": "probe_dns_lookup_time_seconds{project=~\"$project\", app=~\"$app\"}"
    }
   ]
  },
  {
   "title": "Total Sites OK",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 4, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_success{project=~\"$project\", app=~\"$app\"} == 1)"
    }
   ]
  },
  {
   "title": "Total Sites com Falha",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 7, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(probe_success{project=~\"$project\", app=~\"$app\"} == 0)"
    }
   ]
  },
  {
   "title": "Alerta! Site com status code diferente de 200",
   "type": "table",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "probe_http_status_code{project=~\"$project\", app=~\"$app\"}"
    },
    {
     "expr": "sum(probe_http_duration_seconds{project=~\"$project\", app=~\"$app\"}) by (instance)"
    }
   ]
  },
  {
   "title": "Expired in less than 30 days",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 11, "y": 12 },
   "targets": [
    {
     "expr": "probe_ssl_earliest_cert_expiry{project=~\"$project\", app=~\"$app\"} - time() < (3600 * 24 * 30)"
    }
   ]
  },
  { "title": "Tipos de alertas", "type": "alertlist", "gridPos": { "h": 9, "w": 4, "x": 20, "y": 12 } },
  { "title": "Response Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds{project=~\"$project\", app=~\"$app\"}) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Response code change record",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "probe_http_status_code{project=~\"$project\", app=~\"$app\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Sites",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(probe_success{project=~\"$project\", app=~\"$app\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total Sites OK",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "count(probe_success{project=~\"$project\", app=~\"$app\"} == 1)"
    }
   ]
  },
  {
   "title": "Total com Falha",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 32 },
   "targets": [
    {
     "expr": "count(probe_success{project=~\"$project\", app=~\"$app\"} == 0)"
    }
   ]
  }
 ]
}